# Generated by Django 4.1.4 on 2022-12-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("def", "Definition"),
                    ("thm", "Theorem"),
                    ("lem", "Lemma"),
                    ("exp", "Example"),
                    ("prb", "Problem"),
                    ("cor", "Corollary"),
                ],
                default="def",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
