# Generated by Django 4.1.4 on 2022-12-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_block_block_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[("def", "Definition"), ("res", "Result"), ("prb", "Problem")],
                max_length=3,
            ),
        ),
    ]
