# Generated by Django 4.1.4 on 2022-12-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_block_block_type"),
    ]

    operations = [
        migrations.RenameModel(old_name="Block", new_name="Mblock",),
        migrations.AlterModelOptions(
            name="mblock", options={"ordering": ("-created_at",)},
        ),
    ]
