# Generated by Django 4.1.4 on 2022-12-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_block_type_mblock_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=355)),
                ("slug", models.SlugField()),
                ("preview_text", models.TextField()),
            ],
        ),
    ]
