# Generated by Django 4.1.4 on 2022-12-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="mblock",
            name="referenced_by",
            field=models.ManyToManyField(blank=True, to="blog.note"),
        ),
        migrations.AlterField(
            model_name="mblock",
            name="type",
            field=models.CharField(
                choices=[("Def", "Definition"), ("Res", "Result"), ("Exp", "Example")],
                max_length=3,
            ),
        ),
    ]
