# Generated by Django 4.1.4 on 2022-12-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_mblock_referenced_by_alter_mblock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="prerequisites",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.note",
            ),
        ),
        migrations.AlterField(
            model_name="mblock",
            name="referenced_by",
            field=models.ManyToManyField(blank=True, null=True, to="blog.note"),
        ),
        migrations.AlterField(
            model_name="mblock", name="title", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="note", name="title", field=models.CharField(max_length=255),
        ),
    ]
