# Generated by Django 4.1.4 on 2022-12-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_note_prerequisites_alter_mblock_referenced_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mblock",
            name="referenced_by",
            field=models.ManyToManyField(blank=True, to="blog.note"),
        ),
    ]
